[build]
builder = "NIXPACKS"
buildCommand = "bundle install --clean --force"

[deploy]
startCommand = "RAILS_ENV=production bundle exec rake db:setup_for_railway && RAILS_ENV=production bundle exec puma -C config/puma.rb"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

