[phases.setup]
nixPkgs = ["...", "postgresql"]

[phases.build]
cmds = ["bundle install --clean --force"]

[start]
cmd = "RAILS_ENV=production bundle exec rake db:setup_for_railway && RAILS_ENV=production bundle exec puma -C config/puma.rb"

[variables]
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "true"
RAILS_SERVE_STATIC_FILES = "true"

